// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-eH9dh4eyR4shcwN4iUxqCgmSDmofO4',
    appId: '1:36931071790:web:b957c8bfbdee3d3bcf14bf',
    messagingSenderId: '36931071790',
    projectId: 'blue-wave-8f742',
    authDomain: 'blue-wave-8f742.firebaseapp.com',
    databaseURL: 'https://blue-wave-8f742-default-rtdb.firebaseio.com',
    storageBucket: 'blue-wave-8f742.firebasestorage.app',
    measurementId: 'G-M54ERM9T8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVt1sgSU1CUgtRd1N99abFypE4H6qm5SU',
    appId: '1:36931071790:android:64c82ebebfaabef2cf14bf',
    messagingSenderId: '36931071790',
    projectId: 'blue-wave-8f742',
    databaseURL: 'https://blue-wave-8f742-default-rtdb.firebaseio.com',
    storageBucket: 'blue-wave-8f742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD67wZNJb0N1bFwyIyAG28Y0BXNsiAuloM',
    appId: '1:36931071790:ios:325248054ea02d02cf14bf',
    messagingSenderId: '36931071790',
    projectId: 'blue-wave-8f742',
    databaseURL: 'https://blue-wave-8f742-default-rtdb.firebaseio.com',
    storageBucket: 'blue-wave-8f742.firebasestorage.app',
    androidClientId: '36931071790-a4igqqaj3hbalgp8lslj1mp4i5b505dj.apps.googleusercontent.com',
    iosClientId: '36931071790-99ij8e978vbcr06536aqrja94bhrslfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD67wZNJb0N1bFwyIyAG28Y0BXNsiAuloM',
    appId: '1:36931071790:ios:325248054ea02d02cf14bf',
    messagingSenderId: '36931071790',
    projectId: 'blue-wave-8f742',
    databaseURL: 'https://blue-wave-8f742-default-rtdb.firebaseio.com',
    storageBucket: 'blue-wave-8f742.firebasestorage.app',
    androidClientId: '36931071790-a4igqqaj3hbalgp8lslj1mp4i5b505dj.apps.googleusercontent.com',
    iosClientId: '36931071790-99ij8e978vbcr06536aqrja94bhrslfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc-eH9dh4eyR4shcwN4iUxqCgmSDmofO4',
    appId: '1:36931071790:web:0c2a853abca07db8cf14bf',
    messagingSenderId: '36931071790',
    projectId: 'blue-wave-8f742',
    authDomain: 'blue-wave-8f742.firebaseapp.com',
    databaseURL: 'https://blue-wave-8f742-default-rtdb.firebaseio.com',
    storageBucket: 'blue-wave-8f742.firebasestorage.app',
    measurementId: 'G-W8F1KWF0GK',
  );

}